sudo: required

services:
  - docker

env:
  - DOCKER_REPO_SLUG=lolivei/pynode

script:
  - docker build -t $DOCKER_REPO_SLUG:latest .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_REPO_SLUG:latest
